@startuml
' RF05 - Gerenciamento de Fornecedores

left to right direction

skinparam actorStyle awesome

title RF05 - Gerenciamento de Fornecedores

actor Administrador
actor Fornecedor

rectangle "Módulo de Fornecedores" {
    usecase "Cadastrar\nFornecedor" as UC05_1
    usecase "Listar\nFornecedores" as UC05_2
    usecase "Editar\nFornecedor" as UC05_3
    usecase "Excluir\nFornecedor" as UC05_4
}

Administrador --> UC05_1
Administrador --> UC05_2
Administrador --> UC05_3
Administrador --> UC05_4

Fornecedor --> UC05_2
Fornecedor --> UC05_3

@enduml
